spring:
  application:
    name: service-A
  datasource:
      url: jdbc:mysql://47.92.113.165:3306/clesun?useUnicode=false&characterEncoding=UTF-8
      username: root
      password: clesun@123456
      driver-class-name: com.mysql.jdbc.Driver
      sql-script-encoding: UTF-8

      type: com.alibaba.druid.pool.DruidDataSource
      filters: stat
      maxActive: 20
      initialSize: 1
      maxWait: 60000
      minIdle: 1
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxOpenPreparedStatements: 20
server:
  port: 8765
eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

mybatis:
  type-aliases-package: com.clesun.bigdataservice.entity
  mapper-locations: classpath:mapper/*.xml
  configuration:
    use-generated-keys: true
    use-column-label: true
    map-underscore-to-camel-case: false
    key-generator-names: SelectKeyGenerator
    use-actual-param-name: false
    lazy-loading-enabled: false
    aggressive-lazy-loading: false


jwt:
  secret_key: clesun_big_data

  ttlMillis: 3600000