package com.clesun.bigdataservice.entity;

public class CDeptRole {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_dept_role.id
     *
     * @mbggenerated Mon Aug 20 09:15:13 CST 2018
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_dept_role.dept_id
     *
     * @mbggenerated Mon Aug 20 09:15:13 CST 2018
     */
    private Long deptId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_dept_role.role_id
     *
     * @mbggenerated Mon Aug 20 09:15:13 CST 2018
     */
    private Long roleId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_dept_role.id
     *
     * @return the value of c_dept_role.id
     *
     * @mbggenerated Mon Aug 20 09:15:13 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_dept_role.id
     *
     * @param id the value for c_dept_role.id
     *
     * @mbggenerated Mon Aug 20 09:15:13 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_dept_role.dept_id
     *
     * @return the value of c_dept_role.dept_id
     *
     * @mbggenerated Mon Aug 20 09:15:13 CST 2018
     */
    public Long getDeptId() {
        return deptId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_dept_role.dept_id
     *
     * @param deptId the value for c_dept_role.dept_id
     *
     * @mbggenerated Mon Aug 20 09:15:13 CST 2018
     */
    public void setDeptId(Long deptId) {
        this.deptId = deptId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_dept_role.role_id
     *
     * @return the value of c_dept_role.role_id
     *
     * @mbggenerated Mon Aug 20 09:15:13 CST 2018
     */
    public Long getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_dept_role.role_id
     *
     * @param roleId the value for c_dept_role.role_id
     *
     * @mbggenerated Mon Aug 20 09:15:13 CST 2018
     */
    public void setRoleId(Long roleId) {
        this.roleId = roleId;
    }
}