package com.clesun.bigdataservice.entity;

public class CDeptUser {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_dept_user.id
     *
     * @mbggenerated Mon Aug 20 09:15:13 CST 2018
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_dept_user.dept_id
     *
     * @mbggenerated Mon Aug 20 09:15:13 CST 2018
     */
    private Long deptId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_dept_user.user_id
     *
     * @mbggenerated Mon Aug 20 09:15:13 CST 2018
     */
    private Long userId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_dept_user.id
     *
     * @return the value of c_dept_user.id
     *
     * @mbggenerated Mon Aug 20 09:15:13 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_dept_user.id
     *
     * @param id the value for c_dept_user.id
     *
     * @mbggenerated Mon Aug 20 09:15:13 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_dept_user.dept_id
     *
     * @return the value of c_dept_user.dept_id
     *
     * @mbggenerated Mon Aug 20 09:15:13 CST 2018
     */
    public Long getDeptId() {
        return deptId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_dept_user.dept_id
     *
     * @param deptId the value for c_dept_user.dept_id
     *
     * @mbggenerated Mon Aug 20 09:15:13 CST 2018
     */
    public void setDeptId(Long deptId) {
        this.deptId = deptId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_dept_user.user_id
     *
     * @return the value of c_dept_user.user_id
     *
     * @mbggenerated Mon Aug 20 09:15:13 CST 2018
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_dept_user.user_id
     *
     * @param userId the value for c_dept_user.user_id
     *
     * @mbggenerated Mon Aug 20 09:15:13 CST 2018
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }
}