package com.clesun.bigdataservice.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class CModuleExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table c_module
     *
     * @mbggenerated Mon Aug 20 09:15:13 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table c_module
     *
     * @mbggenerated Mon Aug 20 09:15:13 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table c_module
     *
     * @mbggenerated Mon Aug 20 09:15:13 CST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table c_module
     *
     * @mbggenerated Mon Aug 20 09:15:13 CST 2018
     */
    protected int offset = -1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table c_module
     *
     * @mbggenerated Mon Aug 20 09:15:13 CST 2018
     */
    protected int limit = -1;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_module
     *
     * @mbggenerated Mon Aug 20 09:15:13 CST 2018
     */
    public CModuleExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_module
     *
     * @mbggenerated Mon Aug 20 09:15:13 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_module
     *
     * @mbggenerated Mon Aug 20 09:15:13 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_module
     *
     * @mbggenerated Mon Aug 20 09:15:13 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_module
     *
     * @mbggenerated Mon Aug 20 09:15:13 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_module
     *
     * @mbggenerated Mon Aug 20 09:15:13 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_module
     *
     * @mbggenerated Mon Aug 20 09:15:13 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_module
     *
     * @mbggenerated Mon Aug 20 09:15:13 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_module
     *
     * @mbggenerated Mon Aug 20 09:15:13 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_module
     *
     * @mbggenerated Mon Aug 20 09:15:13 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_module
     *
     * @mbggenerated Mon Aug 20 09:15:13 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_module
     *
     * @mbggenerated Mon Aug 20 09:15:13 CST 2018
     */
    public void setOffset(int offset) {
        this.offset=offset;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_module
     *
     * @mbggenerated Mon Aug 20 09:15:13 CST 2018
     */
    public int getOffset() {
        return offset;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_module
     *
     * @mbggenerated Mon Aug 20 09:15:13 CST 2018
     */
    public void setLimit(int limit) {
        this.limit=limit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_module
     *
     * @mbggenerated Mon Aug 20 09:15:13 CST 2018
     */
    public int getLimit() {
        return limit;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table c_module
     *
     * @mbggenerated Mon Aug 20 09:15:13 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        public void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        public void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andModIdIsNull() {
            addCriterion("mod_id is null");
            return (Criteria) this;
        }

        public Criteria andModIdIsNotNull() {
            addCriterion("mod_id is not null");
            return (Criteria) this;
        }

        public Criteria andModIdEqualTo(Long value) {
            addCriterion("mod_id =", value, "modId");
            return (Criteria) this;
        }

        public Criteria andModIdNotEqualTo(Long value) {
            addCriterion("mod_id <>", value, "modId");
            return (Criteria) this;
        }

        public Criteria andModIdGreaterThan(Long value) {
            addCriterion("mod_id >", value, "modId");
            return (Criteria) this;
        }

        public Criteria andModIdGreaterThanOrEqualTo(Long value) {
            addCriterion("mod_id >=", value, "modId");
            return (Criteria) this;
        }

        public Criteria andModIdLessThan(Long value) {
            addCriterion("mod_id <", value, "modId");
            return (Criteria) this;
        }

        public Criteria andModIdLessThanOrEqualTo(Long value) {
            addCriterion("mod_id <=", value, "modId");
            return (Criteria) this;
        }

        public Criteria andModIdIn(List<Long> values) {
            addCriterion("mod_id in", values, "modId");
            return (Criteria) this;
        }

        public Criteria andModIdNotIn(List<Long> values) {
            addCriterion("mod_id not in", values, "modId");
            return (Criteria) this;
        }

        public Criteria andModIdBetween(Long value1, Long value2) {
            addCriterion("mod_id between", value1, value2, "modId");
            return (Criteria) this;
        }

        public Criteria andModIdNotBetween(Long value1, Long value2) {
            addCriterion("mod_id not between", value1, value2, "modId");
            return (Criteria) this;
        }

        public Criteria andModCodeIsNull() {
            addCriterion("mod_code is null");
            return (Criteria) this;
        }

        public Criteria andModCodeIsNotNull() {
            addCriterion("mod_code is not null");
            return (Criteria) this;
        }

        public Criteria andModCodeEqualTo(String value) {
            addCriterion("mod_code =", value, "modCode");
            return (Criteria) this;
        }

        public Criteria andModCodeNotEqualTo(String value) {
            addCriterion("mod_code <>", value, "modCode");
            return (Criteria) this;
        }

        public Criteria andModCodeGreaterThan(String value) {
            addCriterion("mod_code >", value, "modCode");
            return (Criteria) this;
        }

        public Criteria andModCodeGreaterThanOrEqualTo(String value) {
            addCriterion("mod_code >=", value, "modCode");
            return (Criteria) this;
        }

        public Criteria andModCodeLessThan(String value) {
            addCriterion("mod_code <", value, "modCode");
            return (Criteria) this;
        }

        public Criteria andModCodeLessThanOrEqualTo(String value) {
            addCriterion("mod_code <=", value, "modCode");
            return (Criteria) this;
        }

        public Criteria andModCodeLike(String value) {
            addCriterion("mod_code like", value, "modCode");
            return (Criteria) this;
        }

        public Criteria andModCodeNotLike(String value) {
            addCriterion("mod_code not like", value, "modCode");
            return (Criteria) this;
        }

        public Criteria andModCodeIn(List<String> values) {
            addCriterion("mod_code in", values, "modCode");
            return (Criteria) this;
        }

        public Criteria andModCodeNotIn(List<String> values) {
            addCriterion("mod_code not in", values, "modCode");
            return (Criteria) this;
        }

        public Criteria andModCodeBetween(String value1, String value2) {
            addCriterion("mod_code between", value1, value2, "modCode");
            return (Criteria) this;
        }

        public Criteria andModCodeNotBetween(String value1, String value2) {
            addCriterion("mod_code not between", value1, value2, "modCode");
            return (Criteria) this;
        }

        public Criteria andModNameIsNull() {
            addCriterion("mod_name is null");
            return (Criteria) this;
        }

        public Criteria andModNameIsNotNull() {
            addCriterion("mod_name is not null");
            return (Criteria) this;
        }

        public Criteria andModNameEqualTo(String value) {
            addCriterion("mod_name =", value, "modName");
            return (Criteria) this;
        }

        public Criteria andModNameNotEqualTo(String value) {
            addCriterion("mod_name <>", value, "modName");
            return (Criteria) this;
        }

        public Criteria andModNameGreaterThan(String value) {
            addCriterion("mod_name >", value, "modName");
            return (Criteria) this;
        }

        public Criteria andModNameGreaterThanOrEqualTo(String value) {
            addCriterion("mod_name >=", value, "modName");
            return (Criteria) this;
        }

        public Criteria andModNameLessThan(String value) {
            addCriterion("mod_name <", value, "modName");
            return (Criteria) this;
        }

        public Criteria andModNameLessThanOrEqualTo(String value) {
            addCriterion("mod_name <=", value, "modName");
            return (Criteria) this;
        }

        public Criteria andModNameLike(String value) {
            addCriterion("mod_name like", value, "modName");
            return (Criteria) this;
        }

        public Criteria andModNameNotLike(String value) {
            addCriterion("mod_name not like", value, "modName");
            return (Criteria) this;
        }

        public Criteria andModNameIn(List<String> values) {
            addCriterion("mod_name in", values, "modName");
            return (Criteria) this;
        }

        public Criteria andModNameNotIn(List<String> values) {
            addCriterion("mod_name not in", values, "modName");
            return (Criteria) this;
        }

        public Criteria andModNameBetween(String value1, String value2) {
            addCriterion("mod_name between", value1, value2, "modName");
            return (Criteria) this;
        }

        public Criteria andModNameNotBetween(String value1, String value2) {
            addCriterion("mod_name not between", value1, value2, "modName");
            return (Criteria) this;
        }

        public Criteria andModParentCodeIsNull() {
            addCriterion("mod_parent_code is null");
            return (Criteria) this;
        }

        public Criteria andModParentCodeIsNotNull() {
            addCriterion("mod_parent_code is not null");
            return (Criteria) this;
        }

        public Criteria andModParentCodeEqualTo(String value) {
            addCriterion("mod_parent_code =", value, "modParentCode");
            return (Criteria) this;
        }

        public Criteria andModParentCodeNotEqualTo(String value) {
            addCriterion("mod_parent_code <>", value, "modParentCode");
            return (Criteria) this;
        }

        public Criteria andModParentCodeGreaterThan(String value) {
            addCriterion("mod_parent_code >", value, "modParentCode");
            return (Criteria) this;
        }

        public Criteria andModParentCodeGreaterThanOrEqualTo(String value) {
            addCriterion("mod_parent_code >=", value, "modParentCode");
            return (Criteria) this;
        }

        public Criteria andModParentCodeLessThan(String value) {
            addCriterion("mod_parent_code <", value, "modParentCode");
            return (Criteria) this;
        }

        public Criteria andModParentCodeLessThanOrEqualTo(String value) {
            addCriterion("mod_parent_code <=", value, "modParentCode");
            return (Criteria) this;
        }

        public Criteria andModParentCodeLike(String value) {
            addCriterion("mod_parent_code like", value, "modParentCode");
            return (Criteria) this;
        }

        public Criteria andModParentCodeNotLike(String value) {
            addCriterion("mod_parent_code not like", value, "modParentCode");
            return (Criteria) this;
        }

        public Criteria andModParentCodeIn(List<String> values) {
            addCriterion("mod_parent_code in", values, "modParentCode");
            return (Criteria) this;
        }

        public Criteria andModParentCodeNotIn(List<String> values) {
            addCriterion("mod_parent_code not in", values, "modParentCode");
            return (Criteria) this;
        }

        public Criteria andModParentCodeBetween(String value1, String value2) {
            addCriterion("mod_parent_code between", value1, value2, "modParentCode");
            return (Criteria) this;
        }

        public Criteria andModParentCodeNotBetween(String value1, String value2) {
            addCriterion("mod_parent_code not between", value1, value2, "modParentCode");
            return (Criteria) this;
        }

        public Criteria andModUrlIsNull() {
            addCriterion("mod_url is null");
            return (Criteria) this;
        }

        public Criteria andModUrlIsNotNull() {
            addCriterion("mod_url is not null");
            return (Criteria) this;
        }

        public Criteria andModUrlEqualTo(String value) {
            addCriterion("mod_url =", value, "modUrl");
            return (Criteria) this;
        }

        public Criteria andModUrlNotEqualTo(String value) {
            addCriterion("mod_url <>", value, "modUrl");
            return (Criteria) this;
        }

        public Criteria andModUrlGreaterThan(String value) {
            addCriterion("mod_url >", value, "modUrl");
            return (Criteria) this;
        }

        public Criteria andModUrlGreaterThanOrEqualTo(String value) {
            addCriterion("mod_url >=", value, "modUrl");
            return (Criteria) this;
        }

        public Criteria andModUrlLessThan(String value) {
            addCriterion("mod_url <", value, "modUrl");
            return (Criteria) this;
        }

        public Criteria andModUrlLessThanOrEqualTo(String value) {
            addCriterion("mod_url <=", value, "modUrl");
            return (Criteria) this;
        }

        public Criteria andModUrlLike(String value) {
            addCriterion("mod_url like", value, "modUrl");
            return (Criteria) this;
        }

        public Criteria andModUrlNotLike(String value) {
            addCriterion("mod_url not like", value, "modUrl");
            return (Criteria) this;
        }

        public Criteria andModUrlIn(List<String> values) {
            addCriterion("mod_url in", values, "modUrl");
            return (Criteria) this;
        }

        public Criteria andModUrlNotIn(List<String> values) {
            addCriterion("mod_url not in", values, "modUrl");
            return (Criteria) this;
        }

        public Criteria andModUrlBetween(String value1, String value2) {
            addCriterion("mod_url between", value1, value2, "modUrl");
            return (Criteria) this;
        }

        public Criteria andModUrlNotBetween(String value1, String value2) {
            addCriterion("mod_url not between", value1, value2, "modUrl");
            return (Criteria) this;
        }

        public Criteria andModIconIsNull() {
            addCriterion("mod_icon is null");
            return (Criteria) this;
        }

        public Criteria andModIconIsNotNull() {
            addCriterion("mod_icon is not null");
            return (Criteria) this;
        }

        public Criteria andModIconEqualTo(String value) {
            addCriterion("mod_icon =", value, "modIcon");
            return (Criteria) this;
        }

        public Criteria andModIconNotEqualTo(String value) {
            addCriterion("mod_icon <>", value, "modIcon");
            return (Criteria) this;
        }

        public Criteria andModIconGreaterThan(String value) {
            addCriterion("mod_icon >", value, "modIcon");
            return (Criteria) this;
        }

        public Criteria andModIconGreaterThanOrEqualTo(String value) {
            addCriterion("mod_icon >=", value, "modIcon");
            return (Criteria) this;
        }

        public Criteria andModIconLessThan(String value) {
            addCriterion("mod_icon <", value, "modIcon");
            return (Criteria) this;
        }

        public Criteria andModIconLessThanOrEqualTo(String value) {
            addCriterion("mod_icon <=", value, "modIcon");
            return (Criteria) this;
        }

        public Criteria andModIconLike(String value) {
            addCriterion("mod_icon like", value, "modIcon");
            return (Criteria) this;
        }

        public Criteria andModIconNotLike(String value) {
            addCriterion("mod_icon not like", value, "modIcon");
            return (Criteria) this;
        }

        public Criteria andModIconIn(List<String> values) {
            addCriterion("mod_icon in", values, "modIcon");
            return (Criteria) this;
        }

        public Criteria andModIconNotIn(List<String> values) {
            addCriterion("mod_icon not in", values, "modIcon");
            return (Criteria) this;
        }

        public Criteria andModIconBetween(String value1, String value2) {
            addCriterion("mod_icon between", value1, value2, "modIcon");
            return (Criteria) this;
        }

        public Criteria andModIconNotBetween(String value1, String value2) {
            addCriterion("mod_icon not between", value1, value2, "modIcon");
            return (Criteria) this;
        }

        public Criteria andModTypeIsNull() {
            addCriterion("mod_type is null");
            return (Criteria) this;
        }

        public Criteria andModTypeIsNotNull() {
            addCriterion("mod_type is not null");
            return (Criteria) this;
        }

        public Criteria andModTypeEqualTo(Integer value) {
            addCriterion("mod_type =", value, "modType");
            return (Criteria) this;
        }

        public Criteria andModTypeNotEqualTo(Integer value) {
            addCriterion("mod_type <>", value, "modType");
            return (Criteria) this;
        }

        public Criteria andModTypeGreaterThan(Integer value) {
            addCriterion("mod_type >", value, "modType");
            return (Criteria) this;
        }

        public Criteria andModTypeGreaterThanOrEqualTo(Integer value) {
            addCriterion("mod_type >=", value, "modType");
            return (Criteria) this;
        }

        public Criteria andModTypeLessThan(Integer value) {
            addCriterion("mod_type <", value, "modType");
            return (Criteria) this;
        }

        public Criteria andModTypeLessThanOrEqualTo(Integer value) {
            addCriterion("mod_type <=", value, "modType");
            return (Criteria) this;
        }

        public Criteria andModTypeIn(List<Integer> values) {
            addCriterion("mod_type in", values, "modType");
            return (Criteria) this;
        }

        public Criteria andModTypeNotIn(List<Integer> values) {
            addCriterion("mod_type not in", values, "modType");
            return (Criteria) this;
        }

        public Criteria andModTypeBetween(Integer value1, Integer value2) {
            addCriterion("mod_type between", value1, value2, "modType");
            return (Criteria) this;
        }

        public Criteria andModTypeNotBetween(Integer value1, Integer value2) {
            addCriterion("mod_type not between", value1, value2, "modType");
            return (Criteria) this;
        }

        public Criteria andModPermissionIsNull() {
            addCriterion("mod_permission is null");
            return (Criteria) this;
        }

        public Criteria andModPermissionIsNotNull() {
            addCriterion("mod_permission is not null");
            return (Criteria) this;
        }

        public Criteria andModPermissionEqualTo(String value) {
            addCriterion("mod_permission =", value, "modPermission");
            return (Criteria) this;
        }

        public Criteria andModPermissionNotEqualTo(String value) {
            addCriterion("mod_permission <>", value, "modPermission");
            return (Criteria) this;
        }

        public Criteria andModPermissionGreaterThan(String value) {
            addCriterion("mod_permission >", value, "modPermission");
            return (Criteria) this;
        }

        public Criteria andModPermissionGreaterThanOrEqualTo(String value) {
            addCriterion("mod_permission >=", value, "modPermission");
            return (Criteria) this;
        }

        public Criteria andModPermissionLessThan(String value) {
            addCriterion("mod_permission <", value, "modPermission");
            return (Criteria) this;
        }

        public Criteria andModPermissionLessThanOrEqualTo(String value) {
            addCriterion("mod_permission <=", value, "modPermission");
            return (Criteria) this;
        }

        public Criteria andModPermissionLike(String value) {
            addCriterion("mod_permission like", value, "modPermission");
            return (Criteria) this;
        }

        public Criteria andModPermissionNotLike(String value) {
            addCriterion("mod_permission not like", value, "modPermission");
            return (Criteria) this;
        }

        public Criteria andModPermissionIn(List<String> values) {
            addCriterion("mod_permission in", values, "modPermission");
            return (Criteria) this;
        }

        public Criteria andModPermissionNotIn(List<String> values) {
            addCriterion("mod_permission not in", values, "modPermission");
            return (Criteria) this;
        }

        public Criteria andModPermissionBetween(String value1, String value2) {
            addCriterion("mod_permission between", value1, value2, "modPermission");
            return (Criteria) this;
        }

        public Criteria andModPermissionNotBetween(String value1, String value2) {
            addCriterion("mod_permission not between", value1, value2, "modPermission");
            return (Criteria) this;
        }

        public Criteria andOrderNumIsNull() {
            addCriterion("order_num is null");
            return (Criteria) this;
        }

        public Criteria andOrderNumIsNotNull() {
            addCriterion("order_num is not null");
            return (Criteria) this;
        }

        public Criteria andOrderNumEqualTo(Integer value) {
            addCriterion("order_num =", value, "orderNum");
            return (Criteria) this;
        }

        public Criteria andOrderNumNotEqualTo(Integer value) {
            addCriterion("order_num <>", value, "orderNum");
            return (Criteria) this;
        }

        public Criteria andOrderNumGreaterThan(Integer value) {
            addCriterion("order_num >", value, "orderNum");
            return (Criteria) this;
        }

        public Criteria andOrderNumGreaterThanOrEqualTo(Integer value) {
            addCriterion("order_num >=", value, "orderNum");
            return (Criteria) this;
        }

        public Criteria andOrderNumLessThan(Integer value) {
            addCriterion("order_num <", value, "orderNum");
            return (Criteria) this;
        }

        public Criteria andOrderNumLessThanOrEqualTo(Integer value) {
            addCriterion("order_num <=", value, "orderNum");
            return (Criteria) this;
        }

        public Criteria andOrderNumIn(List<Integer> values) {
            addCriterion("order_num in", values, "orderNum");
            return (Criteria) this;
        }

        public Criteria andOrderNumNotIn(List<Integer> values) {
            addCriterion("order_num not in", values, "orderNum");
            return (Criteria) this;
        }

        public Criteria andOrderNumBetween(Integer value1, Integer value2) {
            addCriterion("order_num between", value1, value2, "orderNum");
            return (Criteria) this;
        }

        public Criteria andOrderNumNotBetween(Integer value1, Integer value2) {
            addCriterion("order_num not between", value1, value2, "orderNum");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNull() {
            addCriterion("update_time is null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNotNull() {
            addCriterion("update_time is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeEqualTo(Date value) {
            addCriterion("update_time =", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotEqualTo(Date value) {
            addCriterion("update_time <>", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThan(Date value) {
            addCriterion("update_time >", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("update_time >=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThan(Date value) {
            addCriterion("update_time <", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThanOrEqualTo(Date value) {
            addCriterion("update_time <=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIn(List<Date> values) {
            addCriterion("update_time in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotIn(List<Date> values) {
            addCriterion("update_time not in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeBetween(Date value1, Date value2) {
            addCriterion("update_time between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotBetween(Date value1, Date value2) {
            addCriterion("update_time not between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andSysIdIsNull() {
            addCriterion("sys_id is null");
            return (Criteria) this;
        }

        public Criteria andSysIdIsNotNull() {
            addCriterion("sys_id is not null");
            return (Criteria) this;
        }

        public Criteria andSysIdEqualTo(Long value) {
            addCriterion("sys_id =", value, "sysId");
            return (Criteria) this;
        }

        public Criteria andSysIdNotEqualTo(Long value) {
            addCriterion("sys_id <>", value, "sysId");
            return (Criteria) this;
        }

        public Criteria andSysIdGreaterThan(Long value) {
            addCriterion("sys_id >", value, "sysId");
            return (Criteria) this;
        }

        public Criteria andSysIdGreaterThanOrEqualTo(Long value) {
            addCriterion("sys_id >=", value, "sysId");
            return (Criteria) this;
        }

        public Criteria andSysIdLessThan(Long value) {
            addCriterion("sys_id <", value, "sysId");
            return (Criteria) this;
        }

        public Criteria andSysIdLessThanOrEqualTo(Long value) {
            addCriterion("sys_id <=", value, "sysId");
            return (Criteria) this;
        }

        public Criteria andSysIdIn(List<Long> values) {
            addCriterion("sys_id in", values, "sysId");
            return (Criteria) this;
        }

        public Criteria andSysIdNotIn(List<Long> values) {
            addCriterion("sys_id not in", values, "sysId");
            return (Criteria) this;
        }

        public Criteria andSysIdBetween(Long value1, Long value2) {
            addCriterion("sys_id between", value1, value2, "sysId");
            return (Criteria) this;
        }

        public Criteria andSysIdNotBetween(Long value1, Long value2) {
            addCriterion("sys_id not between", value1, value2, "sysId");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table c_module
     *
     * @mbggenerated do_not_delete_during_merge Mon Aug 20 09:15:13 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table c_module
     *
     * @mbggenerated Mon Aug 20 09:15:13 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}