package com.clesun.bigdataservice.entity;

import java.util.Date;

public class CModule {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_module.mod_id
     *
     * @mbggenerated Mon Aug 20 09:15:13 CST 2018
     */
    private Long modId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_module.mod_code
     *
     * @mbggenerated Mon Aug 20 09:15:13 CST 2018
     */
    private String modCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_module.mod_name
     *
     * @mbggenerated Mon Aug 20 09:15:13 CST 2018
     */
    private String modName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_module.mod_parent_code
     *
     * @mbggenerated Mon Aug 20 09:15:13 CST 2018
     */
    private String modParentCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_module.mod_url
     *
     * @mbggenerated Mon Aug 20 09:15:13 CST 2018
     */
    private String modUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_module.mod_icon
     *
     * @mbggenerated Mon Aug 20 09:15:13 CST 2018
     */
    private String modIcon;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_module.mod_type
     *
     * @mbggenerated Mon Aug 20 09:15:13 CST 2018
     */
    private Integer modType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_module.mod_permission
     *
     * @mbggenerated Mon Aug 20 09:15:13 CST 2018
     */
    private String modPermission;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_module.order_num
     *
     * @mbggenerated Mon Aug 20 09:15:13 CST 2018
     */
    private Integer orderNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_module.create_time
     *
     * @mbggenerated Mon Aug 20 09:15:13 CST 2018
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_module.update_time
     *
     * @mbggenerated Mon Aug 20 09:15:13 CST 2018
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_module.sys_id
     *
     * @mbggenerated Mon Aug 20 09:15:13 CST 2018
     */
    private Long sysId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_module.mod_id
     *
     * @return the value of c_module.mod_id
     *
     * @mbggenerated Mon Aug 20 09:15:13 CST 2018
     */
    public Long getModId() {
        return modId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_module.mod_id
     *
     * @param modId the value for c_module.mod_id
     *
     * @mbggenerated Mon Aug 20 09:15:13 CST 2018
     */
    public void setModId(Long modId) {
        this.modId = modId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_module.mod_code
     *
     * @return the value of c_module.mod_code
     *
     * @mbggenerated Mon Aug 20 09:15:13 CST 2018
     */
    public String getModCode() {
        return modCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_module.mod_code
     *
     * @param modCode the value for c_module.mod_code
     *
     * @mbggenerated Mon Aug 20 09:15:13 CST 2018
     */
    public void setModCode(String modCode) {
        this.modCode = modCode == null ? null : modCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_module.mod_name
     *
     * @return the value of c_module.mod_name
     *
     * @mbggenerated Mon Aug 20 09:15:13 CST 2018
     */
    public String getModName() {
        return modName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_module.mod_name
     *
     * @param modName the value for c_module.mod_name
     *
     * @mbggenerated Mon Aug 20 09:15:13 CST 2018
     */
    public void setModName(String modName) {
        this.modName = modName == null ? null : modName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_module.mod_parent_code
     *
     * @return the value of c_module.mod_parent_code
     *
     * @mbggenerated Mon Aug 20 09:15:13 CST 2018
     */
    public String getModParentCode() {
        return modParentCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_module.mod_parent_code
     *
     * @param modParentCode the value for c_module.mod_parent_code
     *
     * @mbggenerated Mon Aug 20 09:15:13 CST 2018
     */
    public void setModParentCode(String modParentCode) {
        this.modParentCode = modParentCode == null ? null : modParentCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_module.mod_url
     *
     * @return the value of c_module.mod_url
     *
     * @mbggenerated Mon Aug 20 09:15:13 CST 2018
     */
    public String getModUrl() {
        return modUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_module.mod_url
     *
     * @param modUrl the value for c_module.mod_url
     *
     * @mbggenerated Mon Aug 20 09:15:13 CST 2018
     */
    public void setModUrl(String modUrl) {
        this.modUrl = modUrl == null ? null : modUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_module.mod_icon
     *
     * @return the value of c_module.mod_icon
     *
     * @mbggenerated Mon Aug 20 09:15:13 CST 2018
     */
    public String getModIcon() {
        return modIcon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_module.mod_icon
     *
     * @param modIcon the value for c_module.mod_icon
     *
     * @mbggenerated Mon Aug 20 09:15:13 CST 2018
     */
    public void setModIcon(String modIcon) {
        this.modIcon = modIcon == null ? null : modIcon.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_module.mod_type
     *
     * @return the value of c_module.mod_type
     *
     * @mbggenerated Mon Aug 20 09:15:13 CST 2018
     */
    public Integer getModType() {
        return modType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_module.mod_type
     *
     * @param modType the value for c_module.mod_type
     *
     * @mbggenerated Mon Aug 20 09:15:13 CST 2018
     */
    public void setModType(Integer modType) {
        this.modType = modType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_module.mod_permission
     *
     * @return the value of c_module.mod_permission
     *
     * @mbggenerated Mon Aug 20 09:15:13 CST 2018
     */
    public String getModPermission() {
        return modPermission;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_module.mod_permission
     *
     * @param modPermission the value for c_module.mod_permission
     *
     * @mbggenerated Mon Aug 20 09:15:13 CST 2018
     */
    public void setModPermission(String modPermission) {
        this.modPermission = modPermission == null ? null : modPermission.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_module.order_num
     *
     * @return the value of c_module.order_num
     *
     * @mbggenerated Mon Aug 20 09:15:13 CST 2018
     */
    public Integer getOrderNum() {
        return orderNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_module.order_num
     *
     * @param orderNum the value for c_module.order_num
     *
     * @mbggenerated Mon Aug 20 09:15:13 CST 2018
     */
    public void setOrderNum(Integer orderNum) {
        this.orderNum = orderNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_module.create_time
     *
     * @return the value of c_module.create_time
     *
     * @mbggenerated Mon Aug 20 09:15:13 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_module.create_time
     *
     * @param createTime the value for c_module.create_time
     *
     * @mbggenerated Mon Aug 20 09:15:13 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_module.update_time
     *
     * @return the value of c_module.update_time
     *
     * @mbggenerated Mon Aug 20 09:15:13 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_module.update_time
     *
     * @param updateTime the value for c_module.update_time
     *
     * @mbggenerated Mon Aug 20 09:15:13 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_module.sys_id
     *
     * @return the value of c_module.sys_id
     *
     * @mbggenerated Mon Aug 20 09:15:13 CST 2018
     */
    public Long getSysId() {
        return sysId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_module.sys_id
     *
     * @param sysId the value for c_module.sys_id
     *
     * @mbggenerated Mon Aug 20 09:15:13 CST 2018
     */
    public void setSysId(Long sysId) {
        this.sysId = sysId;
    }
}