package com.clesun.bigdataservice.entity;

import java.util.Date;

public class CRole {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_role.role_id
     *
     * @mbggenerated Mon Aug 20 09:15:13 CST 2018
     */
    private Long roleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_role.role_code
     *
     * @mbggenerated Mon Aug 20 09:15:13 CST 2018
     */
    private String roleCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_role.role_name
     *
     * @mbggenerated Mon Aug 20 09:15:13 CST 2018
     */
    private String roleName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_role.role_desc
     *
     * @mbggenerated Mon Aug 20 09:15:13 CST 2018
     */
    private String roleDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_role.farm_id
     *
     * @mbggenerated Mon Aug 20 09:15:13 CST 2018
     */
    private Long farmId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_role.create_user_id
     *
     * @mbggenerated Mon Aug 20 09:15:13 CST 2018
     */
    private Long createUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_role.create_time
     *
     * @mbggenerated Mon Aug 20 09:15:13 CST 2018
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_role.update_time
     *
     * @mbggenerated Mon Aug 20 09:15:13 CST 2018
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_role.role_id
     *
     * @return the value of c_role.role_id
     *
     * @mbggenerated Mon Aug 20 09:15:13 CST 2018
     */
    public Long getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_role.role_id
     *
     * @param roleId the value for c_role.role_id
     *
     * @mbggenerated Mon Aug 20 09:15:13 CST 2018
     */
    public void setRoleId(Long roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_role.role_code
     *
     * @return the value of c_role.role_code
     *
     * @mbggenerated Mon Aug 20 09:15:13 CST 2018
     */
    public String getRoleCode() {
        return roleCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_role.role_code
     *
     * @param roleCode the value for c_role.role_code
     *
     * @mbggenerated Mon Aug 20 09:15:13 CST 2018
     */
    public void setRoleCode(String roleCode) {
        this.roleCode = roleCode == null ? null : roleCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_role.role_name
     *
     * @return the value of c_role.role_name
     *
     * @mbggenerated Mon Aug 20 09:15:13 CST 2018
     */
    public String getRoleName() {
        return roleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_role.role_name
     *
     * @param roleName the value for c_role.role_name
     *
     * @mbggenerated Mon Aug 20 09:15:13 CST 2018
     */
    public void setRoleName(String roleName) {
        this.roleName = roleName == null ? null : roleName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_role.role_desc
     *
     * @return the value of c_role.role_desc
     *
     * @mbggenerated Mon Aug 20 09:15:13 CST 2018
     */
    public String getRoleDesc() {
        return roleDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_role.role_desc
     *
     * @param roleDesc the value for c_role.role_desc
     *
     * @mbggenerated Mon Aug 20 09:15:13 CST 2018
     */
    public void setRoleDesc(String roleDesc) {
        this.roleDesc = roleDesc == null ? null : roleDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_role.farm_id
     *
     * @return the value of c_role.farm_id
     *
     * @mbggenerated Mon Aug 20 09:15:13 CST 2018
     */
    public Long getFarmId() {
        return farmId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_role.farm_id
     *
     * @param farmId the value for c_role.farm_id
     *
     * @mbggenerated Mon Aug 20 09:15:13 CST 2018
     */
    public void setFarmId(Long farmId) {
        this.farmId = farmId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_role.create_user_id
     *
     * @return the value of c_role.create_user_id
     *
     * @mbggenerated Mon Aug 20 09:15:13 CST 2018
     */
    public Long getCreateUserId() {
        return createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_role.create_user_id
     *
     * @param createUserId the value for c_role.create_user_id
     *
     * @mbggenerated Mon Aug 20 09:15:13 CST 2018
     */
    public void setCreateUserId(Long createUserId) {
        this.createUserId = createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_role.create_time
     *
     * @return the value of c_role.create_time
     *
     * @mbggenerated Mon Aug 20 09:15:13 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_role.create_time
     *
     * @param createTime the value for c_role.create_time
     *
     * @mbggenerated Mon Aug 20 09:15:13 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_role.update_time
     *
     * @return the value of c_role.update_time
     *
     * @mbggenerated Mon Aug 20 09:15:13 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_role.update_time
     *
     * @param updateTime the value for c_role.update_time
     *
     * @mbggenerated Mon Aug 20 09:15:13 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}