package com.clesun.bigdataservice.entity;

public class CRoleModule {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_role_module.id
     *
     * @mbggenerated Mon Aug 20 09:15:13 CST 2018
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_role_module.role_id
     *
     * @mbggenerated Mon Aug 20 09:15:13 CST 2018
     */
    private Long roleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_role_module.module_id
     *
     * @mbggenerated Mon Aug 20 09:15:13 CST 2018
     */
    private Long moduleId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_role_module.id
     *
     * @return the value of c_role_module.id
     *
     * @mbggenerated Mon Aug 20 09:15:13 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_role_module.id
     *
     * @param id the value for c_role_module.id
     *
     * @mbggenerated Mon Aug 20 09:15:13 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_role_module.role_id
     *
     * @return the value of c_role_module.role_id
     *
     * @mbggenerated Mon Aug 20 09:15:13 CST 2018
     */
    public Long getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_role_module.role_id
     *
     * @param roleId the value for c_role_module.role_id
     *
     * @mbggenerated Mon Aug 20 09:15:13 CST 2018
     */
    public void setRoleId(Long roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_role_module.module_id
     *
     * @return the value of c_role_module.module_id
     *
     * @mbggenerated Mon Aug 20 09:15:13 CST 2018
     */
    public Long getModuleId() {
        return moduleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_role_module.module_id
     *
     * @param moduleId the value for c_role_module.module_id
     *
     * @mbggenerated Mon Aug 20 09:15:13 CST 2018
     */
    public void setModuleId(Long moduleId) {
        this.moduleId = moduleId;
    }
}