package com.clesun.bigdataservice.entity;

import java.util.Date;

public class CUser {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_user.user_id
     *
     * @mbggenerated Mon Aug 20 09:15:13 CST 2018
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_user.user_name
     *
     * @mbggenerated Mon Aug 20 09:15:13 CST 2018
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_user.head_icon
     *
     * @mbggenerated Mon Aug 20 09:15:13 CST 2018
     */
    private String headIcon;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_user.nick_name
     *
     * @mbggenerated Mon Aug 20 09:15:13 CST 2018
     */
    private String nickName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_user.sex
     *
     * @mbggenerated Mon Aug 20 09:15:13 CST 2018
     */
    private String sex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_user.user_password
     *
     * @mbggenerated Mon Aug 20 09:15:13 CST 2018
     */
    private String userPassword;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_user.phone_no
     *
     * @mbggenerated Mon Aug 20 09:15:13 CST 2018
     */
    private String phoneNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_user.tel
     *
     * @mbggenerated Mon Aug 20 09:15:13 CST 2018
     */
    private String tel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_user.email
     *
     * @mbggenerated Mon Aug 20 09:15:13 CST 2018
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_user.age
     *
     * @mbggenerated Mon Aug 20 09:15:13 CST 2018
     */
    private Integer age;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_user.birthday
     *
     * @mbggenerated Mon Aug 20 09:15:13 CST 2018
     */
    private Date birthday;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_user.create_time
     *
     * @mbggenerated Mon Aug 20 09:15:13 CST 2018
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_user.state
     *
     * @mbggenerated Mon Aug 20 09:15:13 CST 2018
     */
    private Integer state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_user.role_id
     *
     * @mbggenerated Mon Aug 20 09:15:13 CST 2018
     */
    private Long roleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_user.role_name
     *
     * @mbggenerated Mon Aug 20 09:15:13 CST 2018
     */
    private String roleName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_user.pri_desc
     *
     * @mbggenerated Mon Aug 20 09:15:13 CST 2018
     */
    private String priDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_user.user_property
     *
     * @mbggenerated Mon Aug 20 09:15:13 CST 2018
     */
    private String userProperty;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_user.farm_id
     *
     * @mbggenerated Mon Aug 20 09:15:13 CST 2018
     */
    private String farmId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_user.registertype
     *
     * @mbggenerated Mon Aug 20 09:15:13 CST 2018
     */
    private Integer registertype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_user.qq
     *
     * @mbggenerated Mon Aug 20 09:15:13 CST 2018
     */
    private String qq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_user.msn
     *
     * @mbggenerated Mon Aug 20 09:15:13 CST 2018
     */
    private String msn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_user.weibo
     *
     * @mbggenerated Mon Aug 20 09:15:13 CST 2018
     */
    private String weibo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_user.wx
     *
     * @mbggenerated Mon Aug 20 09:15:13 CST 2018
     */
    private String wx;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_user.create_user_id
     *
     * @mbggenerated Mon Aug 20 09:15:13 CST 2018
     */
    private Long createUserId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_user.user_id
     *
     * @return the value of c_user.user_id
     *
     * @mbggenerated Mon Aug 20 09:15:13 CST 2018
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_user.user_id
     *
     * @param userId the value for c_user.user_id
     *
     * @mbggenerated Mon Aug 20 09:15:13 CST 2018
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_user.user_name
     *
     * @return the value of c_user.user_name
     *
     * @mbggenerated Mon Aug 20 09:15:13 CST 2018
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_user.user_name
     *
     * @param userName the value for c_user.user_name
     *
     * @mbggenerated Mon Aug 20 09:15:13 CST 2018
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_user.head_icon
     *
     * @return the value of c_user.head_icon
     *
     * @mbggenerated Mon Aug 20 09:15:13 CST 2018
     */
    public String getHeadIcon() {
        return headIcon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_user.head_icon
     *
     * @param headIcon the value for c_user.head_icon
     *
     * @mbggenerated Mon Aug 20 09:15:13 CST 2018
     */
    public void setHeadIcon(String headIcon) {
        this.headIcon = headIcon == null ? null : headIcon.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_user.nick_name
     *
     * @return the value of c_user.nick_name
     *
     * @mbggenerated Mon Aug 20 09:15:13 CST 2018
     */
    public String getNickName() {
        return nickName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_user.nick_name
     *
     * @param nickName the value for c_user.nick_name
     *
     * @mbggenerated Mon Aug 20 09:15:13 CST 2018
     */
    public void setNickName(String nickName) {
        this.nickName = nickName == null ? null : nickName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_user.sex
     *
     * @return the value of c_user.sex
     *
     * @mbggenerated Mon Aug 20 09:15:13 CST 2018
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_user.sex
     *
     * @param sex the value for c_user.sex
     *
     * @mbggenerated Mon Aug 20 09:15:13 CST 2018
     */
    public void setSex(String sex) {
        this.sex = sex == null ? null : sex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_user.user_password
     *
     * @return the value of c_user.user_password
     *
     * @mbggenerated Mon Aug 20 09:15:13 CST 2018
     */
    public String getUserPassword() {
        return userPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_user.user_password
     *
     * @param userPassword the value for c_user.user_password
     *
     * @mbggenerated Mon Aug 20 09:15:13 CST 2018
     */
    public void setUserPassword(String userPassword) {
        this.userPassword = userPassword == null ? null : userPassword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_user.phone_no
     *
     * @return the value of c_user.phone_no
     *
     * @mbggenerated Mon Aug 20 09:15:13 CST 2018
     */
    public String getPhoneNo() {
        return phoneNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_user.phone_no
     *
     * @param phoneNo the value for c_user.phone_no
     *
     * @mbggenerated Mon Aug 20 09:15:13 CST 2018
     */
    public void setPhoneNo(String phoneNo) {
        this.phoneNo = phoneNo == null ? null : phoneNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_user.tel
     *
     * @return the value of c_user.tel
     *
     * @mbggenerated Mon Aug 20 09:15:13 CST 2018
     */
    public String getTel() {
        return tel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_user.tel
     *
     * @param tel the value for c_user.tel
     *
     * @mbggenerated Mon Aug 20 09:15:13 CST 2018
     */
    public void setTel(String tel) {
        this.tel = tel == null ? null : tel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_user.email
     *
     * @return the value of c_user.email
     *
     * @mbggenerated Mon Aug 20 09:15:13 CST 2018
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_user.email
     *
     * @param email the value for c_user.email
     *
     * @mbggenerated Mon Aug 20 09:15:13 CST 2018
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_user.age
     *
     * @return the value of c_user.age
     *
     * @mbggenerated Mon Aug 20 09:15:13 CST 2018
     */
    public Integer getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_user.age
     *
     * @param age the value for c_user.age
     *
     * @mbggenerated Mon Aug 20 09:15:13 CST 2018
     */
    public void setAge(Integer age) {
        this.age = age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_user.birthday
     *
     * @return the value of c_user.birthday
     *
     * @mbggenerated Mon Aug 20 09:15:13 CST 2018
     */
    public Date getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_user.birthday
     *
     * @param birthday the value for c_user.birthday
     *
     * @mbggenerated Mon Aug 20 09:15:13 CST 2018
     */
    public void setBirthday(Date birthday) {
        this.birthday = birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_user.create_time
     *
     * @return the value of c_user.create_time
     *
     * @mbggenerated Mon Aug 20 09:15:13 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_user.create_time
     *
     * @param createTime the value for c_user.create_time
     *
     * @mbggenerated Mon Aug 20 09:15:13 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_user.state
     *
     * @return the value of c_user.state
     *
     * @mbggenerated Mon Aug 20 09:15:13 CST 2018
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_user.state
     *
     * @param state the value for c_user.state
     *
     * @mbggenerated Mon Aug 20 09:15:13 CST 2018
     */
    public void setState(Integer state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_user.role_id
     *
     * @return the value of c_user.role_id
     *
     * @mbggenerated Mon Aug 20 09:15:13 CST 2018
     */
    public Long getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_user.role_id
     *
     * @param roleId the value for c_user.role_id
     *
     * @mbggenerated Mon Aug 20 09:15:13 CST 2018
     */
    public void setRoleId(Long roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_user.role_name
     *
     * @return the value of c_user.role_name
     *
     * @mbggenerated Mon Aug 20 09:15:13 CST 2018
     */
    public String getRoleName() {
        return roleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_user.role_name
     *
     * @param roleName the value for c_user.role_name
     *
     * @mbggenerated Mon Aug 20 09:15:13 CST 2018
     */
    public void setRoleName(String roleName) {
        this.roleName = roleName == null ? null : roleName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_user.pri_desc
     *
     * @return the value of c_user.pri_desc
     *
     * @mbggenerated Mon Aug 20 09:15:13 CST 2018
     */
    public String getPriDesc() {
        return priDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_user.pri_desc
     *
     * @param priDesc the value for c_user.pri_desc
     *
     * @mbggenerated Mon Aug 20 09:15:13 CST 2018
     */
    public void setPriDesc(String priDesc) {
        this.priDesc = priDesc == null ? null : priDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_user.user_property
     *
     * @return the value of c_user.user_property
     *
     * @mbggenerated Mon Aug 20 09:15:13 CST 2018
     */
    public String getUserProperty() {
        return userProperty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_user.user_property
     *
     * @param userProperty the value for c_user.user_property
     *
     * @mbggenerated Mon Aug 20 09:15:13 CST 2018
     */
    public void setUserProperty(String userProperty) {
        this.userProperty = userProperty == null ? null : userProperty.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_user.farm_id
     *
     * @return the value of c_user.farm_id
     *
     * @mbggenerated Mon Aug 20 09:15:13 CST 2018
     */
    public String getFarmId() {
        return farmId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_user.farm_id
     *
     * @param farmId the value for c_user.farm_id
     *
     * @mbggenerated Mon Aug 20 09:15:13 CST 2018
     */
    public void setFarmId(String farmId) {
        this.farmId = farmId == null ? null : farmId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_user.registertype
     *
     * @return the value of c_user.registertype
     *
     * @mbggenerated Mon Aug 20 09:15:13 CST 2018
     */
    public Integer getRegistertype() {
        return registertype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_user.registertype
     *
     * @param registertype the value for c_user.registertype
     *
     * @mbggenerated Mon Aug 20 09:15:13 CST 2018
     */
    public void setRegistertype(Integer registertype) {
        this.registertype = registertype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_user.qq
     *
     * @return the value of c_user.qq
     *
     * @mbggenerated Mon Aug 20 09:15:13 CST 2018
     */
    public String getQq() {
        return qq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_user.qq
     *
     * @param qq the value for c_user.qq
     *
     * @mbggenerated Mon Aug 20 09:15:13 CST 2018
     */
    public void setQq(String qq) {
        this.qq = qq == null ? null : qq.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_user.msn
     *
     * @return the value of c_user.msn
     *
     * @mbggenerated Mon Aug 20 09:15:13 CST 2018
     */
    public String getMsn() {
        return msn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_user.msn
     *
     * @param msn the value for c_user.msn
     *
     * @mbggenerated Mon Aug 20 09:15:13 CST 2018
     */
    public void setMsn(String msn) {
        this.msn = msn == null ? null : msn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_user.weibo
     *
     * @return the value of c_user.weibo
     *
     * @mbggenerated Mon Aug 20 09:15:13 CST 2018
     */
    public String getWeibo() {
        return weibo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_user.weibo
     *
     * @param weibo the value for c_user.weibo
     *
     * @mbggenerated Mon Aug 20 09:15:13 CST 2018
     */
    public void setWeibo(String weibo) {
        this.weibo = weibo == null ? null : weibo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_user.wx
     *
     * @return the value of c_user.wx
     *
     * @mbggenerated Mon Aug 20 09:15:13 CST 2018
     */
    public String getWx() {
        return wx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_user.wx
     *
     * @param wx the value for c_user.wx
     *
     * @mbggenerated Mon Aug 20 09:15:13 CST 2018
     */
    public void setWx(String wx) {
        this.wx = wx == null ? null : wx.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_user.create_user_id
     *
     * @return the value of c_user.create_user_id
     *
     * @mbggenerated Mon Aug 20 09:15:13 CST 2018
     */
    public Long getCreateUserId() {
        return createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_user.create_user_id
     *
     * @param createUserId the value for c_user.create_user_id
     *
     * @mbggenerated Mon Aug 20 09:15:13 CST 2018
     */
    public void setCreateUserId(Long createUserId) {
        this.createUserId = createUserId;
    }
}