package com.clesun.bigdataservice.entity;

public class CUserRole {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_user_role.ur_id
     *
     * @mbggenerated Mon Aug 20 09:15:13 CST 2018
     */
    private Long urId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_user_role.user_id
     *
     * @mbggenerated Mon Aug 20 09:15:13 CST 2018
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_user_role.role_id
     *
     * @mbggenerated Mon Aug 20 09:15:13 CST 2018
     */
    private Long roleId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_user_role.ur_id
     *
     * @return the value of c_user_role.ur_id
     *
     * @mbggenerated Mon Aug 20 09:15:13 CST 2018
     */
    public Long getUrId() {
        return urId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_user_role.ur_id
     *
     * @param urId the value for c_user_role.ur_id
     *
     * @mbggenerated Mon Aug 20 09:15:13 CST 2018
     */
    public void setUrId(Long urId) {
        this.urId = urId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_user_role.user_id
     *
     * @return the value of c_user_role.user_id
     *
     * @mbggenerated Mon Aug 20 09:15:13 CST 2018
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_user_role.user_id
     *
     * @param userId the value for c_user_role.user_id
     *
     * @mbggenerated Mon Aug 20 09:15:13 CST 2018
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_user_role.role_id
     *
     * @return the value of c_user_role.role_id
     *
     * @mbggenerated Mon Aug 20 09:15:13 CST 2018
     */
    public Long getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_user_role.role_id
     *
     * @param roleId the value for c_user_role.role_id
     *
     * @mbggenerated Mon Aug 20 09:15:13 CST 2018
     */
    public void setRoleId(Long roleId) {
        this.roleId = roleId;
    }
}