package com.clesun.bigdataservice.dao;

import com.clesun.bigdataservice.entity.CRoleModule;
import com.clesun.bigdataservice.entity.CRoleModuleExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CRoleModuleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_role_module
     *
     * @mbggenerated Mon Aug 20 09:15:13 CST 2018
     */
    int countByExample(CRoleModuleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_role_module
     *
     * @mbggenerated Mon Aug 20 09:15:13 CST 2018
     */
    int deleteByExample(CRoleModuleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_role_module
     *
     * @mbggenerated Mon Aug 20 09:15:13 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_role_module
     *
     * @mbggenerated Mon Aug 20 09:15:13 CST 2018
     */
    int insert(CRoleModule record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_role_module
     *
     * @mbggenerated Mon Aug 20 09:15:13 CST 2018
     */
    int insertSelective(CRoleModule record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_role_module
     *
     * @mbggenerated Mon Aug 20 09:15:13 CST 2018
     */
    List<CRoleModule> selectByExample(CRoleModuleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_role_module
     *
     * @mbggenerated Mon Aug 20 09:15:13 CST 2018
     */
    CRoleModule selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_role_module
     *
     * @mbggenerated Mon Aug 20 09:15:13 CST 2018
     */
    int updateByExampleSelective(@Param("record") CRoleModule record, @Param("example") CRoleModuleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_role_module
     *
     * @mbggenerated Mon Aug 20 09:15:13 CST 2018
     */
    int updateByExample(@Param("record") CRoleModule record, @Param("example") CRoleModuleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_role_module
     *
     * @mbggenerated Mon Aug 20 09:15:13 CST 2018
     */
    int updateByPrimaryKeySelective(CRoleModule record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_role_module
     *
     * @mbggenerated Mon Aug 20 09:15:13 CST 2018
     */
    int updateByPrimaryKey(CRoleModule record);
}