package com.clesun.bigdataservice.dao;

import com.clesun.bigdataservice.entity.CUserRole;
import com.clesun.bigdataservice.entity.CUserRoleExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CUserRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_user_role
     *
     * @mbggenerated Mon Aug 20 09:15:13 CST 2018
     */
    int countByExample(CUserRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_user_role
     *
     * @mbggenerated Mon Aug 20 09:15:13 CST 2018
     */
    int deleteByExample(CUserRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_user_role
     *
     * @mbggenerated Mon Aug 20 09:15:13 CST 2018
     */
    int deleteByPrimaryKey(Long urId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_user_role
     *
     * @mbggenerated Mon Aug 20 09:15:13 CST 2018
     */
    int insert(CUserRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_user_role
     *
     * @mbggenerated Mon Aug 20 09:15:13 CST 2018
     */
    int insertSelective(CUserRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_user_role
     *
     * @mbggenerated Mon Aug 20 09:15:13 CST 2018
     */
    List<CUserRole> selectByExample(CUserRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_user_role
     *
     * @mbggenerated Mon Aug 20 09:15:13 CST 2018
     */
    CUserRole selectByPrimaryKey(Long urId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_user_role
     *
     * @mbggenerated Mon Aug 20 09:15:13 CST 2018
     */
    int updateByExampleSelective(@Param("record") CUserRole record, @Param("example") CUserRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_user_role
     *
     * @mbggenerated Mon Aug 20 09:15:13 CST 2018
     */
    int updateByExample(@Param("record") CUserRole record, @Param("example") CUserRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_user_role
     *
     * @mbggenerated Mon Aug 20 09:15:13 CST 2018
     */
    int updateByPrimaryKeySelective(CUserRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_user_role
     *
     * @mbggenerated Mon Aug 20 09:15:13 CST 2018
     */
    int updateByPrimaryKey(CUserRole record);
}